on:
  push:
  pull_request:

name: ci

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell || 'sh' }}
    strategy:
      matrix:
        include:
        - name: Build on Ubuntu
          os: ubuntu-latest
        - name: Build on macOS
          os: macos-latest
        - name: Build on Windows
          os: windows-latest
          shell: msys2 {0}
    steps:
      - name: Install MSYS2 (Windows)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          install: curl unzip

      - name: Install elan
        shell: bash
        run: |
          curl -sSfLO https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh
          chmod +x elan-init.sh
          ./elan-init.sh -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v4

      # TODO: investigate why `lake build` deadlocks on macOS
      - name: Build widgets
        run: npm clean-install && npm run build
        working-directory: ./widget
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Build package
        run: lake build ProofWidgets

      - name: Build demos
        run: lake build ProofWidgets.Demos

      - name: Create GitHub release for tag (Ubuntu)
        if: github.ref_type == 'tag' && matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v1

      - name: Upload release archive (Ubuntu)
        if: github.ref_type == 'tag' && matrix.os == 'ubuntu-latest'
        run: lake upload $RELEASE_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ github.ref_name }}
