on:
  push:
  pull_request:

name: ci

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v3.0.0/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
          
      - uses: actions/checkout@v4

      - name: Build package
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: lake build

      - name: Create release for tag
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1

      # TODO: replace with just `lake upload $RELEASE_TAG` when lean4#2713 is fixed
      # References:
      # https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context
      - name: Upload release archive
        if: github.ref_type == 'tag'
        # All our runners are 64-bit ¯\_(ツ)_/¯
        run: |
          tar -c -z -f ./${RUNNER_OS,}-64.tar.gz -C ./build .
          gh release upload $RELEASE_TAG ./${RUNNER_OS,}-64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ github.ref_name }}
          RUNNER_OS: ${{ runner.os }}
